/*
 * IBM Watson IoT Platform Organization Administration REST APIs
 * The Organization Adminstration APIs can be used to configure an organization (including  creating and deleting devices), checking usage, service status and diagnosing device  connection problems. For information on this API, and how to use Watson IoT Platform APIs generally see  [the API documentation](https://console.ng.bluemix.net/docs/services/IoT/reference/api.html). 
 *
 * OpenAPI spec version: 0002
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ibm.wiotp.swagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ibm.wiotp.swagger.model.DeviceExtensionDiagRefs;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DeviceExtensionRefs
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-30T18:06:21.121+01:00")
public class DeviceExtensionRefs {
  @SerializedName("location")
  private String location = null;

  @SerializedName("mgmt")
  private String mgmt = null;

  @SerializedName("diag")
  private DeviceExtensionDiagRefs diag = null;

  public DeviceExtensionRefs location(String location) {
    this.location = location;
    return this;
  }

   /**
   * URI of location extension.
   * @return location
  **/
  @ApiModelProperty(required = true, value = "URI of location extension.")
  public String getLocation() {
    return location;
  }

  public void setLocation(String location) {
    this.location = location;
  }

  public DeviceExtensionRefs mgmt(String mgmt) {
    this.mgmt = mgmt;
    return this;
  }

   /**
   * URI of mgmt extension, if present.
   * @return mgmt
  **/
  @ApiModelProperty(value = "URI of mgmt extension, if present.")
  public String getMgmt() {
    return mgmt;
  }

  public void setMgmt(String mgmt) {
    this.mgmt = mgmt;
  }

  public DeviceExtensionRefs diag(DeviceExtensionDiagRefs diag) {
    this.diag = diag;
    return this;
  }

   /**
   * Get diag
   * @return diag
  **/
  @ApiModelProperty(required = true, value = "")
  public DeviceExtensionDiagRefs getDiag() {
    return diag;
  }

  public void setDiag(DeviceExtensionDiagRefs diag) {
    this.diag = diag;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceExtensionRefs deviceExtensionRefs = (DeviceExtensionRefs) o;
    return Objects.equals(this.location, deviceExtensionRefs.location) &&
        Objects.equals(this.mgmt, deviceExtensionRefs.mgmt) &&
        Objects.equals(this.diag, deviceExtensionRefs.diag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(location, mgmt, diag);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceExtensionRefs {\n");
    
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    mgmt: ").append(toIndentedString(mgmt)).append("\n");
    sb.append("    diag: ").append(toIndentedString(diag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

