/*
 * IBM Watson IoT Platform Organization Administration REST APIs
 * The Organization Adminstration APIs can be used to configure an organization (including  creating and deleting devices), checking usage, service status and diagnosing device  connection problems. For information on this API, and how to use Watson IoT Platform APIs generally see  [the API documentation](https://console.ng.bluemix.net/docs/services/IoT/reference/api.html). 
 *
 * OpenAPI spec version: 0002
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ibm.wiotp.swagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ibm.wiotp.swagger.model.EdgeServices;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * EdgeConfiguration
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-30T18:06:21.121+01:00")
public class EdgeConfiguration {
  @SerializedName("enabled")
  private Boolean enabled = null;

  @SerializedName("architecture")
  private String architecture = null;

  @SerializedName("edgeServices")
  private List<EdgeServices> edgeServices = null;

  public EdgeConfiguration enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Enable Edge
   * @return enabled
  **/
  @ApiModelProperty(value = "Enable Edge")
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public EdgeConfiguration architecture(String architecture) {
    this.architecture = architecture;
    return this;
  }

   /**
   * Architeture
   * @return architecture
  **/
  @ApiModelProperty(value = "Architeture")
  public String getArchitecture() {
    return architecture;
  }

  public void setArchitecture(String architecture) {
    this.architecture = architecture;
  }

  public EdgeConfiguration edgeServices(List<EdgeServices> edgeServices) {
    this.edgeServices = edgeServices;
    return this;
  }

  public EdgeConfiguration addEdgeServicesItem(EdgeServices edgeServicesItem) {
    if (this.edgeServices == null) {
      this.edgeServices = new ArrayList<EdgeServices>();
    }
    this.edgeServices.add(edgeServicesItem);
    return this;
  }

   /**
   * Get edgeServices
   * @return edgeServices
  **/
  @ApiModelProperty(value = "")
  public List<EdgeServices> getEdgeServices() {
    return edgeServices;
  }

  public void setEdgeServices(List<EdgeServices> edgeServices) {
    this.edgeServices = edgeServices;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EdgeConfiguration edgeConfiguration = (EdgeConfiguration) o;
    return Objects.equals(this.enabled, edgeConfiguration.enabled) &&
        Objects.equals(this.architecture, edgeConfiguration.architecture) &&
        Objects.equals(this.edgeServices, edgeConfiguration.edgeServices);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabled, architecture, edgeServices);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EdgeConfiguration {\n");
    
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    architecture: ").append(toIndentedString(architecture)).append("\n");
    sb.append("    edgeServices: ").append(toIndentedString(edgeServices)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

