/*
 * IBM Watson IoT Platform Organization Information Management REST APIs
 * The Information Management APIs can be used to access device event data as well as  get and update device location and obtain weather information for that location. For information on this API, and how to use Watson IoT Platform APIs generally see  [the API documentation](https://console.ng.bluemix.net/docs/services/IoT/reference/api.html).  version: \"0002\" 
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ibm.wiotp.swagger.api;

import com.ibm.wiotp.swagger.ApiException;
import com.ibm.wiotp.swagger.model.ErrorMessage;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DeviceLocationWeatherApi
 */
@Ignore
public class DeviceLocationWeatherApiTest {

    private final DeviceLocationWeatherApi api = new DeviceLocationWeatherApi();

    
    /**
     * Retrieve current meteorological observations for the location associated with your device
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deviceTypesTypeIdDevicesDeviceIdExtsTwcOpsGeocodeGetTest() throws ApiException {
        String typeId = null;
        String deviceId = null;
        Object response = api.deviceTypesTypeIdDevicesDeviceIdExtsTwcOpsGeocodeGet(typeId, deviceId);

        // TODO: test validations
    }
    
}
