/*
 * IBM Watson IoT Platform Organization Administration REST APIs
 * The Organization Adminstration APIs can be used to configure an organization (including  creating and deleting devices), checking usage, service status and diagnosing device  connection problems. For information on this API, and how to use Watson IoT Platform APIs generally see  [the API documentation](https://console.ng.bluemix.net/docs/services/IoT/reference/api.html). 
 *
 * OpenAPI spec version: 0002
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ibm.wiotp.swagger.api;

import com.ibm.wiotp.swagger.ApiException;
import java.math.BigDecimal;
import com.ibm.wiotp.swagger.model.ErrorMessage;
import com.ibm.wiotp.swagger.model.ListOfLogEntries;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DeviceProblemDeterminationApi
 */
@Ignore
public class DeviceProblemDeterminationApiTest {

    private final DeviceProblemDeterminationApi api = new DeviceProblemDeterminationApi();

    
    /**
     * List device connection log events
     *
     * List connection log events for a device to aid in diagnosing connectivity problems. The entries record successful connection, unsuccessful connection attempts, intentional disconnection and server-initiated disconnection.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void logsConnectionGetTest() throws ApiException {
        String typeId = null;
        String deviceId = null;
        BigDecimal limit = null;
        BigDecimal offset = null;
        String fromTime = null;
        String toTime = null;
        ListOfLogEntries response = api.logsConnectionGet(typeId, deviceId, limit, offset, fromTime, toTime);

        // TODO: test validations
    }
    
}
