/*
 * IBM Watson IoT Platform Organization Administration REST APIs
 * The Organization Adminstration APIs can be used to configure an organization (including  creating and deleting devices), checking usage, service status and diagnosing device  connection problems. For information on this API, and how to use Watson IoT Platform APIs generally see  [the API documentation](https://console.ng.bluemix.net/docs/services/IoT/reference/api.html). 
 *
 * OpenAPI spec version: 0002
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ibm.wiotp.swagger.api;

import com.ibm.wiotp.swagger.ApiException;
import com.ibm.wiotp.swagger.model.DataTraffic;
import com.ibm.wiotp.swagger.model.ErrorMessage;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UsageManagementApi
 */
@Ignore
public class UsageManagementApiTest {

    private final UsageManagementApi api = new UsageManagementApi();

    
    /**
     * Retrieve the amount of data used
     *
     * Retrieve the amount of data used
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void usageDataTrafficGetTest() throws ApiException {
        String start = null;
        String end = null;
        Boolean detail = null;
        DataTraffic response = api.usageDataTrafficGet(start, end, detail);

        // TODO: test validations
    }
    
}
